CREATE TABLE IF NOT EXISTS MOVIE
(
    TITLEID         VARCHAR(200),
    TITLETYPE       VARCHAR(255),
    PRIMARYTITLE    VARCHAR(255),
    ORIGINAlTITLE   VARCHAR(255),
    ISADULT         BOOLEAN,
    STARTYEAR       VARCHAR(20),
    ENDYEAR         VARCHAR(20),
    RUNTIME_MINUTES INTEGER,
    GENERES         VARCHAR(255)

) AS
SELECT *
FROM CSVREAD('./seeddata/Titles.csv')
WHERE tconst IS NOT NULL;
CREATE TABLE IF NOT EXISTS CREWANDCAST
(
    NAMEID       VARCHAR(100),
    PRIMARY_NAME VARCHAR(200),
    BIRTHYEAR    VARCHAR(10),
    DEATHYEAR    VARCHAR(10),
    PROFESSION   VARCHAR(200),
    TITLES       VARCHAR(200)
) AS
SELECT *
FROM CSVREAD('./seeddata/CastAndCrew.csv')
where nconst IS NOT NULL;
--CREATE TABLE IF NOT EXISTS TITLE AS SELECT * FROM CSVREAD('./seeddata/title.crew.tsv', null, 'fieldSeparator=' || CHAR(9));
CREATE TABLE IF NOT EXISTS EPISODE
(
    EPISODEID  VARCHAR(100),
    SERIESID   VARCHAR(200),
    SEASONNUM  INTEGER,
    EPISODENUM INTEGER
) AS
SELECT *
FROM CSVREAD('./seeddata/Episode.csv');
CREATE TABLE IF NOT EXISTS RATINGS
(
    TITLEID       VARCHAR(100),
    AVERAGERATING FLOAT,
    NUMVOTES      INTEGER
) AS
SELECT *
FROM CSVREAD('./seeddata/Ratings.csv')
where tconst IS NOT NULL;
--CREATE TABLE IF NOT EXISTS TITLE AS SELECT * FROM CSVREAD('./seeddata/title.akas.tsv', null, 'fieldSeparator=' || CHAR(9));
CREATE TABLE IF NOT EXISTS PRINCIPALS
(
    TITLEID  VARCHAR(20),
    NAMEID   VARCHAR(20),
    CATEGORY VARCHAR(20)
) AS
SELECT *
FROM CSVREAD('./seeddata/Principals.csv')
where tconst IS NOT NULL;
